---
title: "Lecture4_Chapter4"
author: "Cristian Stark"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(coda)
library(devtools)
library(loo)
library(mvtnorm)
library(dagitty) 
library(shape)
library(tidyverse)
library(rethinking)
library(DiagrammeR)
library(dagitty)
```

## Info:
```{r}
## Fork (Earth)
X <- Z -> Y

## Pipe (Water)
X -> Z -> Y

## Collider (Fire)
X -> Z <- Y

## Descendant (Air)
X -> Z -> Y
     |
     A
``` 

## Problem 1:
```{r}
data(foxes)
dlist <- list(Food=standardize(foxes$avgfood),A=standardize(foxes$area),W=standardize(foxes$weight),G=standardize(foxes$groupsize))

mAF <- quap(
  alist(
    Food ~ dnorm(mu,sigma),
    mu <- a + Ba*A,
    a ~ dnorm(0,0.2),
    Ba ~ dnorm(0,1),
    sigma ~ dexp(1)
  ),data=dlist
)
#plot(precis(mAF))

prior_samples = extract.prior(mAF,n=20)
plot(NA,NA,xlim=range(foxes$area),ylim=range(foxes$avgfood))
for (i in 1:20)abline(prior_samples$a[i],prior_samples$Ba[i],col=1)
post_samples = extract.samples(mAF,n=20)
for(i in 1:20) abline(post_samples$a[i],post_samples$Ba[i],col=2)
```

## Problem 2 first part:
```{r}


mFW <- quap(
  alist(
    W ~ dnorm(mu,sigma),
    mu <- a + bF*Food,
    a ~ dnorm(0,0.2),
    bF ~ dnorm(0,0.5),
    sigma ~ dexp(1)
  ),data=dlist
)
plot(precis(mFW))
prior_samples = extract.prior(mFW,n=20)
plot(NA,NA,xlim=range(foxes$avgfood),ylim=range(foxes$weight))
for (i in 1:20)abline(prior_samples$a[i],prior_samples$bF[i],col=1)
post_samples = extract.samples(mFW,n=20)
for(i in 1:20) abline(post_samples$a[i],post_samples$bF[i],col=2)
```
## Problem 2 second part:
```{r}
predictionsA0 <- link(mFW,data=list(Food=c(0)),n=200)
predictionsA1 <- link(mFW,data=list(Food=c(1)),n=200)
hist(predictionsA1-predictionsA0)
```

## Problem 3:
```{r}
#### Scientifically, think about if food is low and group size goes low to high, whats impact on weight
####### then low group, low food to high food

### The below is simplified in which F and G are independent which Dan thinks is wrong, it probably is
mFWNoG <- quap(
  alist(
    W ~ dnorm(mu,sigma),
    mu <- a + bF*Food + bG*G,
    a ~ dnorm(0,0.2),
    bF ~ dnorm(0,0.5),
    bG ~ dnorm(0,0.5),
    sigma ~ dexp(1)
  ),data=dlist
)
plot(precis(mFWNoG))

### To make sense, subtracting Food from G makes sense IF they are correlated. It looks like positive correlation
#### Adding food to system, increases group size keeping weight the same

```